# Generated by Django 6.1.1 on 2026-10-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_low_stock_alert_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('attibute', models.JSONField(default=dict)),
                ('combination_key', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varients', to='store.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sku', 'product'), name='unique_product_varient_combination')],
            },
        ),
    ]
