# Generated by Django 6.1.1 on 2026-10-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productvarient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvarient',
            old_name='attibute',
            new_name='attributes',
        ),
    ]
